spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


logging:
  level:
    root: warn
    com.lrm: info
  file: log/blog-dev.log


