spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

#  devtools:
#    restart:
#      enabled: false

logging:
  level:
    root: info
    com.lrm: debug
  file: log/blog-dev.log

